Issue/15
eshishkin/mentoring-vshamshurin pull request #29
Opened 2020-12-07 16:12 UTC by VladislavShamshurin

Залил все изменения, которые сделал за это время.

2020-12-07 16:12 UTC, VladislavShamshurin commented
Какие-то конфликты появились

2020-12-10 13:12 UTC, eshishkin requested changes
В целом нормально. По коду описал замечания

Из глобального.

- Нужно подтянуть ветки, чтобы устранить конфликт. Вероятно у тебя ветка началась раньше чем текущий master. Нужно сделать pull мастера в свою ветку (issue/15)
- В текущем мастере работают checkstyle & spotbugs, которые проверяют ошибки в коде и оформлении. После исправления конфликтов необходимо будет прогнать проверки (они автоматом прогонятся на гитхабе) локально через mvn clean package (или явно в идее) и поправить замечания. Они там пишутся в человекочитаемом формате. Могут быть проблемы с импортами, поэтому советую настроить идею так, чтобы она импорты форматировала (*).
- Надо бы с именованием вьюшек и html порядок навести. Сейчас встречается варианты как `enginesList.html`, так и `editEngine.html`. Лучше какой-то стандартный подход иметь в этом деле иначе потом появятся еще дюжина вьюшек, которые не понятно к чему относятся.
Предлагаю
  - разбить все html по директориям - двигатели в engines, машины в cars и так далее. Надо посмотреть, может ли спринг работать с вложенными директориями (вроде может). Если нет, то будем думать.
  - Для каждого файла иметь определенный формат - {domain}_{action}.html. Например `engine_add.html`, `engine_modify.html`, `car_add.html` 


(*) Меняется это в настройках -https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcards-for-class
https://omindu.medium.com/configuring-intellij-idea-to-overcome-checkstyle-wrong-order-for-import-issues-91a32b5096c7
Порядок импортов такой
```
java.*
<пустая строка>
javax.*
<пустая строка>
all other imports
```

2020-12-10 13:12 UTC, eshishkin commented on pom.xml
> +			<scope>provided</scope>
Зачем тут scope provided?

2020-12-10 13:12 UTC, eshishkin commented on pom.xml
> +			<version>1.18.16</version>
Лучше все версии объявлять в секции `<properties>`

```pom
<properties>
  <lombok.version>1.18.16</lombok.version>
</properties>

...
<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<version>${lombok.version}</version>
</dependency>
```

Так банально проще их (версии) отслеживать и менять в случае необходимости, т.к. они все в одном месте.

2020-12-10 13:12 UTC, eshishkin commented on src/main/java/ru/vlad/springApplication/controllers/CarController.java
> +    public ModelAndView createForm(@ModelAttribute("car") Car car) {
По идее, если не ошибаюсь, `@ModelAttribute("car") Car car` особого смысла тут не несет.

2020-12-10 13:12 UTC, eshishkin commented on src/main/java/ru/vlad/springApplication/controllers/UserController.java
> +                : new ResponseEntity<>(HttpStatus.NOT_MODIFIED);
Хмм, тут не совсем корректно применять `NOT_MODIFIED`. Статус обычно используется при `GET` запросах, чтобы сказать браузеру или другому клиенту, что запрашиваемые данные не поменялись и браузер может использоватся данные из своего кэша.

https://developer.mozilla.org/ru/docs/Web/HTTP/Status/304

2020-12-10 13:12 UTC, eshishkin commented on src/main/java/ru/vlad/springApplication/controllers/UserController.java
> +                : new ResponseEntity<>(HttpStatus.NOT_MODIFIED);
Аналогичный коммент по `NOT_MODIFIED`.

2020-12-10 13:12 UTC, eshishkin commented on src/main/java/ru/vlad/springApplication/dto/OtherOption.java
> +    private Set<ModelCar> carsSet;
Тут стоит убрать явное упоминание Hibernate сущности. Оставить либо id-шники, либо `Car`

2020-12-10 13:12 UTC, eshishkin commented on src/main/java/ru/vlad/springApplication/models/ModelOtherOption.java
> +    private List<ModelCar> carsSet;
Тут, кстати, интересный вопрос. Нужна ли нам вообще двунаправленная связь? Вообще, наверное, нет. В том смысле, что для логики не важно знает ли класс `ModelOtherOption` о связанных машинах или нет.

2020-12-10 13:12 UTC, eshishkin commented on src/main/java/ru/vlad/springApplication/services/impl/CarServiceImpl.java
> +    public ModelCar createModelCar(@NotNull Car car) {
Я бы предложил все методы конвертации DTO <-> Model оставить приватными. А также убрать методы `actionCreateModelCar`, `actionUpdateModelCar` и т.п. И перенести всю логику в `create`, `update`, etc

По сути это такая инкапсуляция. Пользователи сервиса (контроллеры в нашем случае) не должны знать как там у сервисов все устроено, какие конвертации надо выполнить и т.п. Контроллер просто вызывает `create`, а что там внутри делается ему без разницы, главное чтобы создал объект и вернул результат. 

Это позволяет в случае необходимости менять логику в одном классе (только в самом сервисе).

2020-12-10 13:12 UTC, eshishkin commented on src/main/java/ru/vlad/springApplication/services/impl/CarServiceImpl.java
> +    public List<ModelCar> readAll() {
Думаю, что стоит возвращать `Car`, вместо `ModelCar`. Внешние пользователи не должны знать о моделях БД. В этом и смысл DTO-шек. Модели БД могут поменятся, не затронув внешний интерфейс сервиса.

2020-12-10 13:12 UTC, eshishkin commented on src/main/java/ru/vlad/springApplication/services/impl/EngineServiceImpl.java
> +public class EngineServiceImpl {
Аналогичные замечания, что и в `CarServiceImpl`

2020-12-10 13:12 UTC, eshishkin commented on src/main/java/ru/vlad/springApplication/services/impl/OtherOptionServiceImpl.java
> +public class OtherOptionServiceImpl {
Аналогичные замечания, что и в `CarServiceImpl`

2020-12-10 13:12 UTC, eshishkin commented on src/main/java/ru/vlad/springApplication/services/impl/TransmissionServiceImpl.java
> +public class TransmissionServiceImpl {
Аналогичные замечания, что и в `CarServiceImpl`

2020-12-10 13:12 UTC, eshishkin commented on src/main/java/ru/vlad/springApplication/services/impl/UserServiceImpl.java
> +public class UserServiceImpl {
Аналогичные замечания, что и в `CarServiceImpl`

2020-12-10 13:12 UTC, eshishkin commented on src/main/java/ru/vlad/springApplication/services/impl/WheelsServiceImpl.java
> +public class WheelsServiceImpl {
Аналогичные замечания, что и в `CarServiceImpl`

2020-12-10 13:12 UTC, eshishkin commented on src/main/resources/templates/carsList.html
> +</form>
Я бы предложил немного сократить область видимости формы. Сейчас у тебя на форме по сути весь список машин и когда ты делаешь submit, то у тебя на сервер передается вся форма, несмотря на то, что удаляешь ты один элемент. Это может и работает, но жрет траффик.

Я бы предложил оформить эту страничку не в виде списка, а в виде таблички (http://htmlbook.ru/html/table) и фоздавать форму только для кнопки delete.

Пример псевдокода

```html
<table>
  <tr>
    <td>...</td>
    <td>...</td>
    <td><form th:method="POST".../></td>
  </tr>
</table>
```
В этом случае у тебя вместо одной формы будет N форм для каждой записи.

2020-12-10 13:12 UTC, eshishkin commented on src/main/resources/templates/enginesList.html
> +<form th:method="POST" th:each ="engine : ${engines}" th:action="@{/engine/delete/{id}(id=${engine.getId()})}">
Аналогично замечание как и в carsList.html

2020-12-10 13:12 UTC, eshishkin commented on src/main/resources/templates/otherOptionsList.html
> +<form th:method="POST" th:each ="otherOption : ${otherOptions}" th:action="@{/otherOption/delete/{id}(id=${otherOption.getId()})}">
Аналогично замечание как и в carsList.html

2020-12-10 13:12 UTC, eshishkin commented on src/main/resources/templates/transmissionsList.html
> +<form th:method="POST" th:each ="transmission : ${transmissions}" th:action="@{/transmission/delete/{id}(id=${transmission.getId()})}">
Аналогичное замечание как и в carsList.html

2020-12-10 13:12 UTC, eshishkin commented on src/main/resources/templates/usersList.html
> +</tr>
Хмм, это же таблица. Тут по идее, это все в `<table>` должно оборачиваться?

https://habr.com/ru/post/435080/
https://www.thymeleaf.org/doc/tutorials/2.1/thymeleafspring.html#listing-seed-starter-data

2020-12-10 13:12 UTC, eshishkin commented on src/main/resources/templates/wheelsList.html
> +<form th:method="POST" th:each ="wheels : ${wheelsList}" th:action="@{/wheels/delete/{id}(id=${wheels.getId()})}">
Аналогичное замечание как и в carsList.html

2020-12-16 15:15 UTC, VladislavShamshurin commented on src/main/java/ru/vlad/springApplication/controllers/CarController.java
> +    public ModelAndView createForm(@ModelAttribute("car") Car car) {
Он добавляет в модель объект с пустыми полями, который я после использую. По другому я мог сделать, убрав @ModellAttribute,
ModelAndView model = new ModelAndView();
model.addAttribute(new Car());

2020-12-16 15:16 UTC, VladislavShamshurin commented on src/main/java/ru/vlad/springApplication/controllers/CarController.java
> +    public ModelAndView createForm(@ModelAttribute("car") Car car) {
Но я так понимаю, спринг и без аннотации добавит объект car в модель

2020-12-16 15:29 UTC, VladislavShamshurin commented on src/main/java/ru/vlad/springApplication/controllers/CarController.java
> +    public ModelAndView createForm(@ModelAttribute("car") Car car) {
исправил

2020-12-16 15:30 UTC, VladislavShamshurin commented on src/main/java/ru/vlad/springApplication/controllers/UserController.java
> +                : new ResponseEntity<>(HttpStatus.NOT_MODIFIED);
исправил

2020-12-16 15:30 UTC, VladislavShamshurin commented on pom.xml
> +			<scope>provided</scope>
исправил

2020-12-16 15:37 UTC, VladislavShamshurin commented on src/main/java/ru/vlad/springApplication/services/impl/CarServiceImpl.java
> +    public List<ModelCar> readAll() {
Я так понял, это сделать вообще во всех методах сервиса?

2020-12-16 15:38 UTC, VladislavShamshurin commented on src/main/java/ru/vlad/springApplication/services/impl/CarServiceImpl.java
> +    public List<ModelCar> readAll() {
Если да, то сделал так

2020-12-25 12:53 UTC, eshishkin reviewed
Выглядит нормально. Осталось поправить только замечания чекстайла и всё.

https://github.com/eshishkin/mentoring-vshamshurin/pull/29/checks

```
Error:  src/main/java/ru/vlad/springApplication/Application.java:[3,8] (imports) UnusedImports: Unused import - java.math.BigDecimal.
Error:  src/main/java/ru/vlad/springApplication/Application.java:[6,8] (imports) UnusedImports: Unused import - ru.vlad.springApplication.dto.Engine.
Error:  src/main/java/ru/vlad/springApplication/services/impl/WheelsServiceImpl.java:[58,19] (naming) AbbreviationAsWordInName: Abbreviation in name 'createDTOOWheels' must contain no more than '4' consecutive capital letters.
Error:  src/main/java/ru/vlad/springApplication/services/impl/TransmissionServiceImpl.java:[6,8] (imports) UnusedImports: Unused import - ru.vlad.springApplication.dto.Car.
Error:  src/main/java/ru/vlad/springApplication/services/impl/TransmissionServiceImpl.java:[8,8] (imports) UnusedImports: Unused import - ru.vlad.springApplication.models.ModelCar.
Error:  src/main/java/ru/vlad/springApplication/services/impl/CarServiceImpl.java:[8,8] (imports) UnusedImports: Unused import - ru.vlad.springApplication.dto.OtherOption.
Error:  src/main/java/ru/vlad/springApplication/models/ModelEngine.java:[61,31] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelEngine.java:[62,28] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelEngine.java:[63,56] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelEngine.java:[64,36] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelTransmission.java:[57,37] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelTransmission.java:[58,28] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelTransmission.java:[59,56] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelTransmission.java:[60,36] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelOtherOption.java:[77,36] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelOtherOption.java:[78,28] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelOtherOption.java:[79,42] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelOtherOption.java:[80,56] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelOtherOption.java:[81,36] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelWheels.java:[68,31] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelWheels.java:[69,28] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelWheels.java:[70,56] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelWheels.java:[71,36] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelUser.java:[62,29] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelUser.java:[63,40] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelUser.java:[64,44] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelUser.java:[65,44] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelUser.java:[66,30] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelCar.java:[15,8] (imports) UnusedImports: Unused import - lombok.AllArgsConstructor.
Error:  src/main/java/ru/vlad/springApplication/models/ModelCar.java:[103,28] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelCar.java:[104,28] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelCar.java:[105,44] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelCar.java:[106,38] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelCar.java:[107,50] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelCar.java:[108,38] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/models/ModelCar.java:[109,75] (whitespace) OperatorWrap: '+' should be on a new line.
Error:  src/main/java/ru/vlad/springApplication/dto/Car.java:[17,18] (naming) MemberName: Name 'wheels_id' must match pattern '^[a-z][a-zA-Z0-9]*$'.
Error:  src/main/java/ru/vlad/springApplication/dto/Car.java:[19,18] (naming) MemberName: Name 'transmission_id' must match pattern '^[a-z][a-zA-Z0-9]*$'.
Error:  src/main/java/ru/vlad/springApplication/dto/Car.java:[21,18] (naming) MemberName: Name 'engine_id' must match pattern '^[a-z][a-zA-Z0-9]*$'.
Error:  src/main/java/ru/vlad/springApplication/controllers/EngineController.java:[31,33] (coding) MultipleStringLiterals: The String "redirect:/engine/list" appears 3 times in the file.
Error:  src/main/java/ru/vlad/springApplication/controllers/UserController.java:[24] (whitespace) EmptyLineSeparator: 'CTOR_DEF' should be separated from previous statement.
Error:  src/main/java/ru/vlad/springApplication/controllers/UserController.java:[56,9] (blocks) NeedBraces: 'if' construct must use '{}'s.
Error:  src/main/java/ru/vlad/springApplication/controllers/UserController.java:[58,9] (blocks) NeedBraces: 'else' construct must use '{}'s.
Error:  src/main/java/ru/vlad/springApplication/controllers/OtherOptionsController.java:[32,33] (coding) MultipleStringLiterals: The String "redirect:/otherOption/list" appears 3 times in the file.
Error:  src/main/java/ru/vlad/springApplication/controllers/WheelsController.java:[32,33] (coding) MultipleStringLiterals: The String "redirect:/wheels/list" appears 3 times in the file.
Error:  src/main/java/ru/vlad/springApplication/controllers/CarController.java:[3,8] (imports) UnusedImports: Unused import - java.util.ArrayList.
Error:  src/main/java/ru/vlad/springApplication/controllers/CarController.java:[4,8] (imports) UnusedImports: Unused import - java.util.List.
Error:  src/main/java/ru/vlad/springApplication/controllers/CarController.java:[14,8] (imports) UnusedImports: Unused import - ru.vlad.springApplication.models.ModelCar.
Error:  src/main/java/ru/vlad/springApplication/controllers/CarController.java:[44,32] (coding) MultipleStringLiterals: The String "wheelsModel" appears 2 times in the file.
Error:  src/main/java/ru/vlad/springApplication/controllers/CarController.java:[45,32] (coding) MultipleStringLiterals: The String "enginesModel" appears 2 times in the file.
Error:  src/main/java/ru/vlad/springApplication/controllers/CarController.java:[46,32] (coding) MultipleStringLiterals: The String "transmissionsModel" appears 2 times in the file.
Error:  src/main/java/ru/vlad/springApplication/controllers/CarController.java:[47,32] (coding) MultipleStringLiterals: The String "otherOptionModel" appears 2 times in the file.
Error:  src/main/java/ru/vlad/springApplication/controller [...]

2020-12-25 13:08 UTC, eshishkin submitted a review, later dismissed

2020-12-29 13:31 UTC, eshishkin approved these changes

2020-12-29 13:32 UTC, merged